/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Especificacion;


import Controladores.ControladorFechasyTipoHabitacion;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Sergio
 */
public class VistaFechas extends javax.swing.JFrame {

    ControladorFechasyTipoHabitacion miControlador;
    
    public VistaFechas() {
        initComponents();
        miControlador = new ControladorFechasyTipoHabitacion(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        botonHabitacion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelFechaLlegada = new javax.swing.JLabel();
        jLabelFechaSalida = new javax.swing.JLabel();
        spinnerDiaEntrada = new javax.swing.JSpinner();
        spinnerAnioEntrada = new javax.swing.JSpinner();
        labelDia = new javax.swing.JLabel();
        labelMes = new javax.swing.JLabel();
        labelAnio = new javax.swing.JLabel();
        spinnerDiaSalida = new javax.swing.JSpinner();
        comboBoxMesSalida = new javax.swing.JComboBox();
        spinnerAnioSalida = new javax.swing.JSpinner();
        jLabelTipoHabitacion = new javax.swing.JLabel();
        comboBoxMesEntrada = new javax.swing.JComboBox();
        jComboBoxTipoHabitacion = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText(" > Habitación > Régimen > Datos personales > Confirmación");

        botonHabitacion.setText("Siguiente");
        botonHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHabitacionActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        jLabel2.setText("Fechas");

        jLabelFechaLlegada.setText("Fecha de llegada :");

        jLabelFechaSalida.setText("Fecha de salida :");

        spinnerDiaEntrada.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        spinnerAnioEntrada.setModel(new javax.swing.SpinnerNumberModel(2015, 1990, 2025, 1));
        spinnerAnioEntrada.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerAnioEntradaActionPerformed(evt);
            }
        });

        labelDia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelDia.setText("Día");

        labelMes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelMes.setText("Mes");

        labelAnio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelAnio.setText("Año");

        spinnerDiaSalida.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        comboBoxMesSalida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        comboBoxMesSalida.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxMesSalidaItemStateChanged(evt);
            }
        });
        comboBoxMesSalida.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                comboBoxMesSalidaActionPerformed(evt);
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        spinnerAnioSalida.setModel(new javax.swing.SpinnerNumberModel(2015, 1990, 2025, 1));
        spinnerAnioSalida.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerAnioSalidaActionPerformed(evt);
            }
        });

        jLabelTipoHabitacion.setText("Tipo de habitación :");

        comboBoxMesEntrada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        comboBoxMesEntrada.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxMesEntradaItemStateChanged(evt);
            }
        });

        jComboBoxTipoHabitacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Individual", "Doble", "Doble de uso individual", "Superior", "Suite", " " }));
        jComboBoxTipoHabitacion.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxTipoHabitacionPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTipoHabitacion)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxTipoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelFechaSalida)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(spinnerDiaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(comboBoxMesSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelFechaLlegada)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spinnerDiaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(comboBoxMesEntrada, 0, 1, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spinnerAnioEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinnerAnioSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelDia)
                        .addGap(73, 73, 73)
                        .addComponent(labelMes)
                        .addGap(71, 71, 71)
                        .addComponent(labelAnio)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDia)
                            .addComponent(labelMes, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerDiaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxMesEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelFechaLlegada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelFechaSalida)
                                    .addComponent(spinnerDiaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBoxMesSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(spinnerAnioEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(33, 33, 33)
                                    .addComponent(spinnerAnioSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoHabitacion)
                    .addComponent(jComboBoxTipoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(botonHabitacion)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHabitacionActionPerformed
        miControlador.habitacion();
    }//GEN-LAST:event_botonHabitacionActionPerformed

    private void spinnerAnioEntradaActionPerformed(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerAnioEntradaActionPerformed
        miControlador.revisaFechasValidasEntrada();
    }//GEN-LAST:event_spinnerAnioEntradaActionPerformed

    private void comboBoxMesSalidaActionPerformed(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboBoxMesSalidaActionPerformed
        miControlador.revisaFechasValidasEntrada();
    }//GEN-LAST:event_comboBoxMesSalidaActionPerformed

    private void spinnerAnioSalidaActionPerformed(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerAnioSalidaActionPerformed
       miControlador.revisaFechasValidasSalida();
    }//GEN-LAST:event_spinnerAnioSalidaActionPerformed

    private void comboBoxMesEntradaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxMesEntradaItemStateChanged
        miControlador.revisaFechasValidasEntrada();
    }//GEN-LAST:event_comboBoxMesEntradaItemStateChanged

    private void comboBoxMesSalidaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxMesSalidaItemStateChanged
        miControlador.revisaFechasValidasSalida();
    }//GEN-LAST:event_comboBoxMesSalidaItemStateChanged

    private void jComboBoxTipoHabitacionPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxTipoHabitacionPopupMenuWillBecomeInvisible
        miControlador.tipoElegido();
    }//GEN-LAST:event_jComboBoxTipoHabitacionPopupMenuWillBecomeInvisible
    
    public ControladorFechasyTipoHabitacion getControlador() {
        return miControlador;
    }
    public String getTipoH() {
       return (String) jComboBoxTipoHabitacion.getSelectedItem();
    }
    public void cambiaModeloSpinnerDiasEntrada(SpinnerNumberModel modelo) {
        spinnerDiaEntrada.setModel(modelo);
        spinnerDiaEntrada.setVisible(true);
    }

    public int getMesIndiceEntrada() {
        return comboBoxMesEntrada.getSelectedIndex();
    }

    public String getMesStringEntrada() {
        return (String) comboBoxMesEntrada.getSelectedItem();
    }

    public int getDiaEntrada() {
        return (int) spinnerDiaEntrada.getValue();
    }

    public int getAnioEntrada() {
        return (int) spinnerAnioEntrada.getValue();
    }

    public void setDiasEntrada(int dia) {
        SpinnerNumberModel modeloDia = (SpinnerNumberModel) spinnerDiaEntrada.getModel();
        modeloDia.setValue(dia);
        this.paint(this.getGraphics()); 

    }
    public void cambiaModeloSpinnerDiasSalida(SpinnerNumberModel modelo) {
        spinnerDiaSalida.setModel(modelo);
    }

    public int getMesSalidaIndice() {
        return comboBoxMesSalida.getSelectedIndex();
    }

    public String getMesSalidaString() {
        return (String) comboBoxMesSalida.getSelectedItem();
    }

    public int getDiaSalida() {
        return (int) spinnerDiaSalida.getValue();
    }

    public int getAnioSalida() {
        return (int) spinnerAnioSalida.getValue();
    }

    public void setDiasSalida(int dia) {
        SpinnerNumberModel modeloDia = (SpinnerNumberModel) spinnerDiaSalida.getModel();
        modeloDia.setValue(dia);
        

    }
   
    
    public String getFechaEntrada() {
        return Integer.toString((int)spinnerDiaEntrada.getValue())+ " / " + 
                (String)comboBoxMesEntrada.getSelectedItem() 
                + " / " + Integer.toString((int)spinnerAnioEntrada.getValue());
    }
    public String getFechaSalida() {
       return Integer.toString((int)spinnerDiaSalida.getValue())+ " / " + 
                        (String)comboBoxMesSalida.getSelectedItem() +
               " / " + Integer.toString((int)spinnerAnioSalida.getValue());
    }
    
    public void errorFechaHoy() {
        
        JOptionPane.showMessageDialog(this, 
                "La fecha introducida es anterior a la fecha actual.",
                "Error de fechas.", JOptionPane.ERROR_MESSAGE);
    }
    
    public void errorFechaSalida() {
        JOptionPane.showMessageDialog(this, 
                "La fecha de salida introducida es anterior a la fecha de entrada.",
                "Error en la fecha de salida.", JOptionPane.ERROR_MESSAGE);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaFechas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaFechas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaFechas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaFechas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaFechas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonHabitacion;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox comboBoxMesEntrada;
    private javax.swing.JComboBox comboBoxMesSalida;
    private javax.swing.JComboBox jComboBoxTipoHabitacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFechaLlegada;
    private javax.swing.JLabel jLabelFechaSalida;
    private javax.swing.JLabel jLabelTipoHabitacion;
    private javax.swing.JLabel labelAnio;
    private javax.swing.JLabel labelDia;
    private javax.swing.JLabel labelMes;
    private javax.swing.JSpinner spinnerAnioEntrada;
    private javax.swing.JSpinner spinnerAnioSalida;
    private javax.swing.JSpinner spinnerDiaEntrada;
    private javax.swing.JSpinner spinnerDiaSalida;
    // End of variables declaration//GEN-END:variables
}
